name: CI

on: [push]

jobs:
  shell:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo ${GITHUB_SHA}

  cmd:
    strategy:
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo %GITHUB_SHA%

