name: CI

on: [push]

jobs:
  shell:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo ${GITHUB_SHA}
    - name: Upload Tools
      uses: actions/upload-artifact@v1
      env:
        file_name: test-${{ matrix.platform }}-${{ github.sha }}
      with:
        name: $file_name
        path: README.md

  cmd:
    strategy:
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      shell: cmd
      run: echo %GITHUB_SHA%
    - name: Upload Tools
      uses: actions/upload-artifact@v1
      with:
        name: test-${{ matrix.platform }}-${{ github.sha }}
        path: README.md
